version: '3'

services:

  db1:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pucsd

  db2:
    image: mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pucsd
    depends_on:
      - db1

  db3:
    image: mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pucsd
    depends_on:
      - db2
